export const ActionTypes = {
  LoginRequest: '[Login Screen] Login Request',
  LoginSuccess: '[Login Effects] Login Success',
  LoginFail: '[Login Effects] Login Fail',
  SignUpRequest: '[SignUp Screen] SignUp Request',
  SignUpSuccess: '[SignUp Effects] SignUp Success',
  SignUpFail: '[SignUp Effects] SignUp Fail',
  ClearCredentials: 'Clear Credentials',
  GetChatMessagesRequest: '[General Screen] Get Messages Request',
  GetChatMessagesSuccess: '[General Effects] Get Messages Success',
  GetChatMessagesFail: '[General Fail] Get Messages Fail',
  SendMessageRequest: '[General Screen] Send Message Request',
  SendMessageFail: '[General Effects] Send Message Fail',
  EditMessageRequest: '[General Screen] Edit Message Request',
  EditMessageFail: '[General Effects] Edit Message Fail',
  DeleteMessageRequest: '[General Screen] Delete Message Request',
  DeleteMessageFail: '[General Effects] Delete Message Fail',
  GetProfileRequest: '[Profile Screen] Get Profile Request',
  GetProfileSuccess: '[Profile Effects] Get Profile Success',
  GetProfileFail: '[Profile Effects] Get Profile Fail',
  EditProfileRequest: '[EditProfile Screen] Edit Profile Request',
  EditProfileFail: '[EditProfile Effects] Edit Profile Fail',
  ChangePasswordRequest: '[ChangePassword Screen] Change Password Request',
  ChangePasswordSuccess: '[ChangePassword Effects] Change Password Success',
  ChangePasswordFail: '[ChangePassword Effects] Change Password Fail',
  DeleteAccountRequest: '[Profile Screen] Delete Account Request',
  DeleteAccountSuccess: '[DeleteAccount Effects] Delete Account Success',
  DeleteAccountFail: '[DeleteAccount Effects] Delete Account Fail',
  GetFollowersRequest: '[Followers Screen] Get Followers Request',
  GetFollowersSuccess: '[Followers Effects] Get Followers Success',
  GetFollowersFail: '[Followers Effects] Get Followers Fail',
  RemoveFollowerRequest: '[Followers Screen] Remove Follower Request',
  RemoveFollowerFail: '[RemoveFollower Effects] Remove Follower Fail',
  GetFollowingsRequest: '[Followings Screen] Get Followings Request',
  GetFollowingsSuccess: '[Followings Effects] Get Followings Success',
  GetFollowingsFail: '[Followings Effects] Get Followings Fail',
  UnfollowRequest: '[Followings Screen] Unfollow Request',
  UnfollowFail: '[Unfollow Effects] Unfollow Fail'
};
