USE [Messenger]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Followers](
	[RelationID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[FollowerID] [int] NOT NULL,
	[Pending] [int] NULL,
 CONSTRAINT [PK_Followers] PRIMARY KEY CLUSTERED 
(
	[RelationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNIQUE_RELATION] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[FollowerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Followers] ADD  CONSTRAINT [DF_Followers_Pending]  DEFAULT ((0)) FOR [Pending]
GO

ALTER TABLE [dbo].[Followers]  WITH CHECK ADD  CONSTRAINT [DIFFERENT_USERS] CHECK  (([UserID]<>[FollowerID]))
GO

ALTER TABLE [dbo].[Followers] CHECK CONSTRAINT [DIFFERENT_USERS]
GO


